### ISSUE TITLE
Not available on Wear OS 3.5?

### ISSUE THREAD

**Issue by daguej** [bryan2894-playgrnd/SimpleWear#15]
The Play store listing for SimpleWear indicates that the Wear app is not compatible with my Pixel watch (Wear OS 3.5 / Android 11) and does not allow me to install the app.

I tried using adb to install the apk manually.  The app launches, but I'm unable to get it to connect.  Launching the watch app just shows "Device not connected".  Unclear if this is an actual incompatibility or just a result of sideloading.

**Comment by ketr4x** [comment]
I have the same problem

**Comment by niksingh710** [comment]
sideloading wear-release.apk also not working.

**Comment by semi710** [comment]
Anyone found any work around?

**Comment by techexplorers123** [comment]
same problem here.
never tried sideloading. but the app is not available on play store on my watch.
Also, i use to use this app. i reseted my watch  yesterday and can't install it anymore.

**Comment by d0lk0** [comment]
The app from google store is not availible for idk what reason, yesterday i sideloaded the 1.5 and downloade on phone the google store one which is availble. It didnt connect because there was a version difference, then i tried downloading both 1.5 releases from github and it connected and worked but didnt get many options of controlling my phone, so downloaded the 1.11 git version and tried to fix it, everything **except "call controller"** and **"wifi, location, data"** works fine and also opening apps doesnt work, havent got time to test it fully, going to fix it somehow maybe, if anyone is interested i can upload the source and also .apk files.

Also im testing it on **Galaxy Watch 4 44mm** running **Wear  OS 3.5**  and **Samsung A51** running **Android 13**.

UPDATE:
I somehow connected, so now everything works except turning on / off wifi and location and sleep timer(im not gonna try that one) 

https://github.com/d0lk0/SimpleWear/releases/tag/v1.11.0_release - working version

**Comment by thewizrd** [comment]
Sorry for no response. Busy with work and personal things. The app should be back on the Play Store as of this morning.
Please let me know of any other issues

**Comment by daguej** [comment]
Thanks for finding some time to look at this.

Can confirm that the Wear app is again available on the Play store and works correctly.
